apiVersion: apps/v1
kind: Deployment
metadata:
  name: butterfly-web-ui
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: butterfly-web-ui
  template:
    metadata:
      labels:
        app: butterfly-web-ui
    spec:
      containers:
      - name: butterfly-web-ui
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/butterfly-web-ui:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: butterfly-web-ui
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: butterfly-web-ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: butterfly-web-ui
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: fly.plaza.red
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: butterfly-web-ui
            port:
              number: 80
  tls:
  - hosts:
    - fly.plaza.red
    secretName: butterfly-web-ui-tls
